//package androidlead.weatherappui.ui.data.mapper
//
//
//import androidlead.weatherappui.ui.data.local.entity.DailyForecastEntity
//import androidlead.weatherappui.ui.domain.model.DailyForecast
//import java.text.SimpleDateFormat
//import java.util.Locale
//
//
//// Map from DailyForecastEntity (database) to DailyForecast domain model
//fun DailyForecastEntity.toDailyForecast(): DailyForecast {
//    return DailyForecast(
//        city = city,
//        dayOfWeek = dayOfWeek,
//        date = date,
//        description = conditionText, // Mapped from conditionText
//        iconUrl = iconUrl,
//        maxTemp = maxTemp,
//        minTemp = minTemp,
//        dailyChanceOfRain = dailyChanceOfRain,
//        pm25 = airQualityIpm25, // Mapped from airQualityIpm25
//        airQualityIndicatorColorHex = airQualityIndicatorColorHex
//    )
//}
//
//// Map from DailyForecast domain model to DailyForecastEntity (for database storage)
//fun DailyForecast.toDailyForecastEntity(): DailyForecastEntity {
//    return DailyForecastEntity(
//        id = 0, // Auto-generated by Room
//        city = city,
//        dayOfWeek = dayOfWeek,
//        date = date,
//        maxTemp = maxTemp,
//        minTemp = minTemp,
//        avgTemp = (maxTemp + minTemp) / 2, // Simple average, adjust if DTO has it
//        conditionText = description, // Mapped to conditionText
//        iconUrl = iconUrl,
//        dailyChanceOfRain = dailyChanceOfRain,
//        airQualityIpm25 = pm25, // Mapped to airQualityIpm25
//        airQualityIndicatorColorHex = airQualityIndicatorColorHex,
//        timestamp = System.currentTimeMillis() // Set current timestamp
//    )
//}